### ISSUE TITLE
Webengage not building on M1 Silicon MacBooks

### ISSUE THREAD

**Issue by mayukheazypg** [WebEngage/webengage-flutter#14]
Hi, so i've been trying to add webengage to my iOS part of application but, I get an error that webengage package cannot build on arm64 simulators. I was hoping to get a resolution to this.

Thank You

webengage_flutter = 1.0.3
flutter = 2.10.4
XCode = 13.3
MacOS = 12.3.1

<img width="1440" alt="Screenshot 2022-04-08 at 12 08 13 AM" src="https://user-images.githubusercontent.com/101384345/162672270-4edaf309-673d-4a8f-9429-56d6933dc842.png">

**Comment by FirdousNath** [comment]
Error (Xcode): Building for iOS Simulator, but linking in dylib built for iOS, file '/Users/imac/Desktop/gcc-app/ios/Pods/WebEngage/xc11/WebEngage.framework/WebEngage' for architecture arm64

**Comment by rohanjsh** [comment]
@SarthakWebEngage @ashwindmk 
Can you check this on priority. 
Flutter version 2.10 and above

**Comment by BhaveshSarwarWebEngage** [comment]
WebEngage pod is included in the podspec provided with the Flutter plugin as dependacy. 
Our WebEngage pod incorporates universal binaries by default, and we have introduced support for XCFramework through a subspec (by using WebEngage/XCFramework in podfile). 

When you are using M1 machine, we propose that they use the XCFramework subspec. 
The customer would not need to take any further steps if we changed the default subspec of WebEngage podspec to include XCFramework. But, until then, you have manually do the changes in WebEngage Flutter plugin podspec 
In order to work with XCFramework

Open and update webengage_flutter plugin (Project-> External Libraries -> Flutter plugin -> WebEngage plugin -> iOS → webengage_flutter.podspec)

Replace WebEngage dependency 
update s.dependency ‘WebEngage' to s.dependency 'WebEngage/XCFramework'

And run 'pod install’
