### ISSUE TITLE
MissingPluginException(No implementation found for method setUserAttribute on channel webengage_flutter)

### ISSUE THREAD

**Issue by FirdousNath** [WebEngage/webengage-flutter#32]
I am getting few crashes on firebase crashlyitcs console. Crashes are very few and occurring on random places whenever I am calling `WebEngagePlugin.setUserAttribute` across my app.

<img width="1202" alt="Screenshot 2023-03-21 at 1 42 27 PM" src="https://user-images.githubusercontent.com/19954996/226549486-0f84fc7f-e12e-4943-a8c5-19ac8e4f8a04.png">

**Comment by MilindWebEngage** [comment]
@FirdousNath can you tell us which version of WebEngage flutter you are using ?
If you have any queries then you can reach out to us on [support@webengage.com](mailto:support@webengage.com).

**Comment by FirdousNath** [comment]
> @FirdousNath can you tell us which version of WebEngage flutter you are using ? If you have any queries then you can reach out to us on [support@webengage.com](mailto:support@webengage.com).

`1.2.1`

**Comment by MilindWebEngage** [comment]
@FirdousNath Please raise a ticket at [support@webengage.com](mailto:support@webengage.com) with all the details.

**Comment by FirdousNath** [comment]
facing this on **1.2.3** as well and almost on all methods like `setUserFirstName`, `setUserPhone`, `trackEvent`, etc methods. I have raised the ticket as well

**Comment by MilindWebEngage** [comment]
@FirdousNath As the issue was caused by Firebase's onBackgroundMessage method, which starts a background isolate, we have updated our plugin to support both foreground and background isolates in the latest version, 1.2.4. 

Please try the latest version and let us know if you face any issues. 

You can try reproducing the steps in version 1.2.3 and then in latest version 1.2.4.
Steps : 
kill the app, 
send a push notification,
click on the push notification, and then fire any WebEngage event. 
In 1.2.3, you will get a 'No Implementation Found' error in the log for the specific event you fired, but in 1.2.4, it has been fixed.
