### ISSUE TITLE
Getting error after webengage swift push setup in flutter

### ISSUE THREAD

**Issue by Siddharth2212** [WebEngage/webengage-flutter#39]
We just started configuring webengage sdk. After doing ios push setup in flutter (swift) I am getting following error:

Error while running app: Could not build the precompiled application for the device.
Error (Xcode): Multiple commands produce '/Users/siddharthsogani/Desktop/apps/spring-mobile-app/build/ios/Debug-iphoneos/XCFrameworkIntermediates/WebEngage/WebEngage.framework'. PFA screenshot of build phases as well. Let me know what should I do to solve this.
<img width="1055" alt="Screenshot 2023-07-29 at 11 29 20 AM" src="https://github.com/WebEngage/webengage-flutter/assets/8082583/f08f5d48-0e83-4fa9-b937-a4ae71e717df">

**Comment by MilindWebEngage** [comment]
@Siddharth2212 The issue seems to arise from having different minimum deployment targets for various targets within your application. For instance, if your main application has a deployment target set to iOS 12.0, while a service extension has a higher deployment target of iOS 16.0, it can lead to conflicts with shared dependencies like the "WebEngage" framework.

Both targets might attempt to fetch different versions of this framework, leading to compatibility issues.

To address this concern effectively, we strongly recommend following these steps: 

1. Check and Modify Deployment Targets: Review the deployment targets for each component of your application, ensuring they are set to the same version. This consistency will prevent dependency clashes. 

2. Update Pods: After modifying the deployment targets, run the "pod update" command again. This action will fetch the appropriate versions of the pods based on the revised targets, resolving the dependency conflict. 

3. Fresh Installation (If Needed): In case you encounter any issues during the update process, consider deleting the "Pods" folder and the "Podfile.lock" file. Then, perform a fresh installation by running "pod install" to ensure a clean slate.
 
We believe that by implementing these measures, you'll be able to resolve the current issue and prevent similar occurrences in the future. 

Should you require any further assistance, have questions, or need additional guidance, please don't hesitate to reach out to us.
